[build]
  # 构建命令
  command = "cd client && npm install && npm run build"
  # 构建输出目录
  publish = "client/dist"

[build.environment]
  # Node.js版本
  NODE_VERSION = "18"

# Netlify Functions配置
[functions]
  # Functions目录
  directory = "netlify/functions"
  # 外部Node模块
  external_node_modules = ["@netlify/neon", "@vercel/postgres", "@vercel/blob", "jsonwebtoken", "bcryptjs", "sequelize", "pg"]

# 重定向规则 (SPA路由支持)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers配置
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# 环境变量设置提示
[build.processing]
  skip_processing = false 