services:
  - type: web
    name: baodeli-backend
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false  # 手动设置
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        sync: false  # 手动设置
      - key: PORT
        value: 3000
    autoDeploy: true
    healthCheckPath: /api/health
    domains:
      - baodeli-backend.onrender.com 